# Generated by Django 5.0.6 on 2024-07-25 21:39

import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climb_gyms', '0002_alter_climbinggyms_rating_alter_ratings_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', djrichtextfield.models.RichTextField(blank=True, max_length=2000, null=True)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to='profile_pics/')),
                ('fav_climb', models.CharField(choices=[('Boulder', 'boulder'), ('Lead', 'lead'), ('Speed', 'speed'), ('Outdoors', 'outdoors')], default='null')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climb_gyms.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
