# Generated by Django 5.0.6 on 2024-08-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
