# Generated by Django 5.0.6 on 2024-08-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.CharField(max_length=75),
        ),
    ]
