# Generated by Django 5.0.6 on 2024-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbinggyms',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
