# Generated by Django 5.0.6 on 2024-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_gyms', '0002_alter_climbinggyms_rating_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
