# Generated by Django 5.0.6 on 2024-08-02 12:18

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_gyms', '0004_alter_climbinggyms_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbinggyms',
            name='maps',
            field=models.CharField(help_text='ex. 59°25\'15.7"N 17°54\'58.3"E"', max_length=100),
        ),
        migrations.AlterField(
            model_name='climbinggyms',
            name='slug',
            field=models.SlugField(help_text='Slug (example: name-of-the-gym)', max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='headimage',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='This will be the front image of the climbing gym', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='climbing-gyms/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.URLField(blank=True, help_text='example: https://www.facebook.com/your-page', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(blank=True, help_text='example: https://www.instagram.com/your-page', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='other',
            field=models.URLField(blank=True, help_text='Other links where people can find more information', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='website',
            field=models.URLField(blank=True, help_text='example: https://www.your-website.com', null=True),
        ),
    ]
